# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bestlelectionever.com
title: Best Election Ever
email: bestlelectionever@gmail.com
author:
description: > # "Register to vote, Requestion Eleciton Day off, Party with your fellow Americans."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/bestelectionevs
