# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://azre.rocks
title: AZRE Community
email: usa.recommunity@gmail.com
author:
description: > # "Join the Arizona Real Estate Community"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/azre_community
