# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://azre.rocks
title: azre
email: usa.recommunity@gmail.com
author:
description: > # "Join the Arizona Real Estate Community"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Apply Now
    url: https://mcbain.typeform.com/to/m0zdFC
